dinrplan/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("planner.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

planner/urls.py
from django.urls import path

from . import views

app_name = "planner"
urlpatterns = [
    path("", views.index, name="index"),
    path("day/edit/<date>", views.EditDayView.as_view(), name="edit_day"),
    path("day/show/<date>", views.ShowDayView.as_view(), name="show_day"),
    path(
        "day/addmeal/<date>/meal_pk/<meal_pk>",
        views.AddMealToDayView.as_view(),
        name="add_meal_to_day",
    ),
    path("meal/edit/<slug:pk>", views.MealUpdateView.as_view(), name="editmeal"),
    path("meal/show/<slug:pk>", views.MealDetailView.as_view(), name="showmeal"),
    path("meal/delete/<slug:pk>", views.MealDeleteView.as_view(), name="delete_meal"),
    path(
        "meal/comment/<slug:pk>",
        views.CommentCreateView.as_view(),
        name="create_comment",
    ),
    path("upload", views.UploadJsonView.as_view(), name="upload"),
    path("update_weeks", views.UpdateDisplayedWeeksView.as_view(), name="update_weeks"),
    path("recipes", views.RecipesView.as_view(), name="recipes"),
    path("weeks", views.WeeksView.as_view(), name="weeks"),
    # Called when dragging from or dropping on a day
    path("drag/<date>", views.DragView.as_view(), name="drag"),
]

planner/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.formats import date_format


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Meal(models.Model):
    """Something that can be cooked and eaten on one or more days.

    A meal is not a recipe to start with; only when it has been submitted through the
    edit form it becomes a recipe and shows up in the recipe list."""

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    source = models.CharField(max_length=200, blank=True)
    persons = models.PositiveSmallIntegerField(
        default=4, validators=[MinValueValidator(1)]
    )
    time = models.CharField(max_length=200, blank=True)
    ingredients = models.TextField(max_length=1000, blank=True)
    steps = models.TextField(max_length=10000, blank=True)
    rating = models.PositiveSmallIntegerField(
        default=0, validators=[MaxValueValidator(5)]
    )
    # is_recipe is True if the meal shall be shown in blue color and in the recipe list.
    is_recipe = models.BooleanField(default=False)
    categories = models.ManyToManyField(Category, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def categories_text(self) -> str:
        return ", ".join(category.name for category in self.categories.all())

    def __str__(self):
        return self.name


class Day(models.Model):
    MEAL_NAME_DELIMITER = ";"

    date = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    meals = models.ManyToManyField(Meal)

    def __str__(self):
        return str(self.date)

    def weekday_name(self) -> str:
        return date_format(self.date, "l")

    def text(self) -> str:
        return self.MEAL_NAME_DELIMITER.join(meal.name for meal in self.meals.all())


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    text = models.TextField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.author}: {self.text}"

planner/forms.py
from django import forms


class UploadFileForm(forms.Form):
    meals = forms.FileField()
    days = forms.FileField()

planner/views.py
import json
from datetime import date
from datetime import timedelta

from django.db.models import Count
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.dateparse import parse_date
from django.views import View
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import UpdateView

from .forms import UploadFileForm
from .models import Category
from .models import Comment
from .models import Day
from .models import Meal

FIRST_WEEK_OFFSET_OPTIONS = [0, 2, 6, 12, 18, 24]
DEFAULT_FIRST_WEEK_OFFSET = 0
NUMBER_OF_WEEKS_TO_SHOW_OPTIONS = [1, 2, 3, 6]
DEFAULT_NUMBER_OF_WEEKS_TO_SHOW = 3


def _get_weeks_and_reset_editing_status(request):
    # When (re)loading the page, reset the editing status of all days so that
    # clicking the edit button opens the edit view for those days again.
    request.session["editing"] = []
    first_week_offset = (
        request.user.first_week_offset
        if request.user.is_authenticated
        else DEFAULT_FIRST_WEEK_OFFSET
    )
    number_of_weeks_to_show = (
        request.user.number_of_weeks_to_show
        if request.user.is_authenticated
        else DEFAULT_NUMBER_OF_WEEKS_TO_SHOW
    )
    week_deltas = range(
        -first_week_offset, -first_week_offset + number_of_weeks_to_show
    )
    monday_current_week = date.today() - timedelta(days=date.today().weekday())
    weeks = []
    if request.user.is_authenticated:
        for week_delta in week_deltas:
            monday = monday_current_week + timedelta(days=week_delta * 7)
            dates = [(monday + timedelta(days=i)) for i in range(7)]
            days = []
            for date_ in dates:
                date_.isoweekday()
                day, _ = Day.objects.get_or_create(date=date_, user=request.user)
                days.append(day)
            weeks.append(days)
    return weeks


def index(request):
    return render(
        request,
        "planner/index.html",
        {
            "weeks": _get_weeks_and_reset_editing_status(request),
            "first_week_offsets": FIRST_WEEK_OFFSET_OPTIONS,
            "numbers_of_weeks_to_show": NUMBER_OF_WEEKS_TO_SHOW_OPTIONS,
        },
    )


class UpdateDisplayedWeeksView(View):
    def post(self, request, *args, **kwargs):
        request.user.first_week_offset = request.POST.get("first-week-offset")
        request.user.number_of_weeks_to_show = request.POST.get(
            "number-of-weeks-to-show"
        )
        request.user.save()

        return HttpResponseRedirect(reverse("planner:weeks"))


class WeeksView(View):
    def get(self, request, *args, **kwargs):
        return render(
            request,
            "planner/weeks.html",
            {"weeks": _get_weeks_and_reset_editing_status(request)},
        )


class MealUpdateView(UpdateView):
    model = Meal
    template_name = "planner/modals/edit_meal.html"
    fields = [
        "name",
        "source",
        "persons",
        "time",
        "ingredients",
        "steps",
        "categories",
        "rating",
    ]
    success_url = "not used since we override form_valid, "
    "but if we don't have this Django throws an exception"

    def form_valid(self, form):
        # Add author to the created Meal object, since it is a mandatory field
        form.instance.author = self.request.user
        # Also set is_recipe to True to show it as blue color and get it to show up in
        # the recipe list
        form.instance.is_recipe = True

        super().form_valid(form)
        # Return the weeks view to htmx, so that the text color updates
        return HttpResponseRedirect(reverse("planner:weeks"))


class MealDetailView(DetailView):
    model = Meal
    template_name = "planner/modals/show_meal.html"
    fields = ["name", "source", "persons", "time", "ingredients", "steps"]


class MealDeleteView(View):
    def get(self, request, *args, **kwargs):
        Meal.objects.get(pk=kwargs["pk"]).delete()
        return HttpResponseRedirect(reverse("planner:recipes"))


class DragView(View):
    """Called when dragging from or dropping on a day, when you want to move a set of
    meals from one day to another."""

    def post(self, request, *args, **kwargs):
        """When dragging from a day, store that date in a variable.
        When dropping on a day, exchange the meals of the source day and the target day.
        """
        event_type = json.loads(request.headers["Triggering-Event"])["type"]
        if event_type == "dragstart":
            request.session["date_dragged_from"] = kwargs["date"]
            return HttpResponse(status=204)
        elif event_type == "drop":
            source_day, _ = Day.objects.get_or_create(
                date=date.fromisoformat(request.session["date_dragged_from"]),
                user=request.user,
            )
            target_day, _ = Day.objects.get_or_create(
                date=date.fromisoformat(kwargs["date"]), user=request.user
            )
            previous_source_day_meals = list(source_day.meals.all())
            source_day.meals.set(target_day.meals.all())
            target_day.meals.set(previous_source_day_meals)
            return HttpResponseRedirect(reverse("planner:weeks"))


class EditDayView(View):
    def get(self, request, *args, **kwargs):
        editing: list = request.session.get("editing", [])
        date_ = kwargs["date"]

        if date_ in editing:
            # If we already were changing this day, store that
            # we are not anymore and return the non-editing day template
            editing.remove(date_)
            request.session["editing"] = editing
            return HttpResponseRedirect(
                reverse("planner:show_day", kwargs={"date": date_})
            )

        # Store that we are currently changing this day
        editing.append(kwargs["date"])
        request.session["editing"] = editing

        day, _ = Day.objects.get_or_create(
            date=date.fromisoformat(date_), user=request.user
        )
        todays_meal_names = [meal.name for meal in day.meals.all()]
        database_meals = [
            meal
            for meal in Meal.objects.filter(author=request.user)
            .annotate(num_days=Count("day"))
            .order_by("-num_days")
            if meal.is_recipe
        ]
        return render(
            request,
            "planner/modals/edit_day.html",
            {
                "day": day,
                "todays_meal_names": todays_meal_names,
                "database_meals": database_meals,
            },
        )

    def post(self, request, *args, **kwargs):
        meal_names = request.POST.getlist("select")  # type: list[str]
        meals = []
        for meal_name in meal_names:
            # Raises MultipleObjectsReturned if the user has managed to create multiple
            # meals in some way
            meal, _ = Meal.objects.get_or_create(author=request.user, name=meal_name)
            meals.append(meal)
        iso_date = date.fromisoformat(kwargs["date"])
        day, _ = Day.objects.get_or_create(date=iso_date, user=request.user)
        day.meals.set(meals)

        return redirect("planner:show_day", date=iso_date)


class AddMealToDayView(View):
    def post(self, request, *args, **kwargs):
        meal = get_object_or_404(Meal, author=request.user, pk=kwargs["meal_pk"])
        iso_date = date.fromisoformat(kwargs["date"])
        day, _ = Day.objects.get_or_create(date=iso_date, user=request.user)
        day.meals.add(meal)
        return HttpResponse(status=200)


class ShowDayView(View):
    def get(self, request, *args, **kwargs):
        day, _ = Day.objects.get_or_create(
            date=date.fromisoformat(kwargs["date"]), user=request.user
        )
        return render(
            request,
            "planner/modals/show_day.html",
            {
                "day": day,
            },
        )


class CommentCreateView(CreateView):
    model = Comment
    template_name = "planner/createcomment.html"
    fields = ["text"]

    def get_success_url(self):
        return reverse("planner:showmeal", kwargs={"pk": self.kwargs["pk"]})

    def form_valid(self, form):
        """Add author to the created Meal object, since it is a mandatory field"""
        form.instance.author = self.request.user

        meal_pk = self.kwargs["pk"]
        meal = get_object_or_404(Meal, pk=meal_pk)
        form.instance.meal = meal

        return super().form_valid(form)


class UploadJsonView(FormView):
    template_name = "planner/upload_json.html"
    form_class = UploadFileForm
    # fields = ["meals", "days"]
    success_url = "/"

    def form_valid(self, form):
        self._upload_meals(self.request.FILES["meals"])
        self._upload_days(self.request.FILES["days"])
        return super().form_valid(form)

    def _upload_meals(self, meals_file):
        bytes = meals_file.read()
        text = bytes.decode("utf-8")
        meal_dicts = json.loads(text)

        for meal_dict in meal_dicts:
            name = meal_dict["name"]
            source = meal_dict["source"]
            persons = meal_dict.get("servings", "") or "4"
            rating = meal_dict.get("rating", "") or "0"
            time = meal_dict["time"]
            ingredients = meal_dict["ingredients"]
            steps = meal_dict["steps"]
            category_names = meal_dict.get("categories", "").split(",")

            categories = []
            if category_names and category_names[0]:
                for category_name in category_names:
                    category, _ = Category.objects.get_or_create(name=category_name)
                    categories.append(category)

planner/templates/planner/createcomment.html
<form method="post" class="comment">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary comment-submit" hx-post="{% url 'planner:create_comment' pk=view.kwargs.pk %}"
        hx-target=".modal-dialog">Submit</button>
</form>

planner/templates/planner/createmeal.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

planner/templates/planner/day_table_row.html
{% now "Y-m-d" as todays_date %}
{% if day.date.isoformat == todays_date %}
<tr class="table-active">
  {% else %}
<tr>
  {% endif %}
  <td class="text-nowrap" style="width:1%">{{day.weekday_name}}<br>{{ day.date.isoformat }}</td>
  <td style="height:1px;" class="day-{{ day.date.isoformat }}"
    hx-post="{% url 'planner:drag' date=day.date.isoformat %}" hx-trigger="dragstart,drop" hx-ext="event-header"
    hx-target="#weeks" draggable="true" ondragover="event.preventDefault()">
    {% include 'planner/modals/show_day.html' with day=day %}
  </td>
  <td class="align-middle" style="width:1%">
    <button class="btn btn-outline-secondary day-{{ day.date.isoformat }} edit-day"
      hx-get="{% url 'planner:edit_day' date=day.date.isoformat %}" hx-target="td.day-{{ day.date.isoformat }}"
      data-bs-toggle="button" aria-pressed="false"><i class="bi bi-pencil"></i></button>
  </td>
</tr>

planner/templates/planner/index.html
{% extends 'base.html' %}



{% block content %}
<div class="container-fluid">
  <form class="d-flex" hx-post="{% url 'planner:update_weeks' %}" hx-target="#weeks" hx-swap="outerHTML"
    hx-trigger="change">
    {% csrf_token %}
    <div class="p-2 m-2">Weeks back:</div>
    <select class="p-2 me-2 mt-2 mb-2" name="first-week-offset">
      {% for first_week_offset in first_week_offsets %}
      {% if user.first_week_offset == first_week_offset %}
      <option value="{{ first_week_offset }}" selected>{{ first_week_offset}}</option>
      {% else %}
      <option value="{{ first_week_offset }}">{{ first_week_offset}}</option>
      {% endif %}
      {% endfor %}
    </select>
    <div class="p-2 me-2 mt-2 mb-2">Weeks to display:</div>
    <select class="p-2 me-4 mt-2 mb-2" name="number-of-weeks-to-show">
      {% for week_count in numbers_of_weeks_to_show %}
      {% if user.number_of_weeks_to_show == week_count %}
      <option value="{{ week_count }}" selected>{{ week_count}}</option>
      {% else %}
      <option value="{{ week_count }}">{{ week_count}}</option>
      {% endif %}
      {% endfor %}
    </select>
  </form>
  {% include 'planner/weeks.html' %}
</div>
{% endblock %}

planner/templates/planner/meal_detail.html
<!--TODO: rename to show_meal_modal.html or similar-->

<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">{{ object.name }}</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <table class="table">
      <tbody>
      <tr>
        <th scope="row" width="1%">Source</th>
        <td><a href="{{ object.source }}">{{ object.source }}</a></td>
      </tr>
      <tr>
        <th scope="row">Persons</th>
        <td>{{ object.persons }}</td>
      </tr>
      <tr>
        <th scope="row">Time</th>
        <td>{{ object.time }}</td>
      </tr>
      <tr>
        <th scope="row">Ingredients</th>
        <td>{{ object.ingredients|linebreaks }}</td>
      </tr>
      <tr>
        <th scope="row">Steps</th>
        <td>{{ object.steps|linebreaks }}</td>
      </tr>
      <tr>
        <th scope="row">Categories</th>
        <td>{{ object.categories_text }}</td>
      </tr>
      <tr>
        <th scope="row">Rating</th>
        <td>{{ object.rating }}</td>
      </tr>
      <tr>
        <th scope="row">
          Comments<br>
          <a class="btn btn-light" href="{% url 'planner:createcomment' pk=object.id %}">
            <i class="bi bi-chat-left-text"></i>
          </a>
        </th>
        <td>
          {% for comment in object.comment_set.all %}
          <div>{{ comment.author }} {{ comment.created_at }}</div>
          <div>{{ comment.text|linebreaks }}</div>
          {% endfor %}
        </td>
      </tr>
      </tbody>
    </table>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <a class="btn btn-primary" hx-get="{% url 'planner:updatemeal' pk=meal.pk%}" hx-target=".modal-dialog" href="#">Edit </a>
  </div>
</div>

planner/templates/planner/recipes.html
{% extends 'base.html' %}


{% block head %}
{% endblock %}

{% block content %}
<table class="table table-striped">
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>Categories</th>
      <th>Rating</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for meal in meals %}
    <tr>
      <td>
        <a class="text-primary" href="#" data-bs-toggle="modal" data-bs-target="#mealModal"
          hx-get="{% url 'planner:showmeal' pk=meal.pk%}" hx-target=".modal-dialog">{{ meal.name }}</a>
      </td>
      <td>
        {% for category in meal.categories.all %}
        {{ category.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
      </td>
      <td>{{ meal.rating }}</td>
      <td>
        <div class="dropdown">
          <button class="btn btn-secondary recipe" type="button" data-bs-toggle="dropdown" data-bs-auto-close="outside"
            aria-expanded="false">
            <i class="bi bi-three-dots"></i>
          </button>
          <ul class="dropdown-menu">
            <li>
              <div class="dropend">
                <a class="dropdown-item add-to-day" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                  Add to day...
                </a>
                <ul class="dropdown-menu">
                  {% for date in dates %}
                  <li><a class="dropdown-item add-meal" href="#"
                      hx-post="{% url 'planner:add_meal_to_day' date=date.isoformat meal_pk=meal.pk %}">
                      {{ date.isoformat }}</a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item text-danger delete" href="{% url 'planner:delete_meal' pk=meal.pk %}"
                onclick="return confirm('Are you sure you want to delete the recipe?');">
                Delete
              </a>
            </li>
          </ul>
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

planner/templates/planner/updatemeal.html
<!--TODO: rename to update_meal_modal.html or similar-->

<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">{{ object.name }}</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <form id="update-meal" action="{% url 'planner:updatemeal' pk=object.pk %}" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save">
    </form>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" form="update-meal" class="btn btn-primary">Save changes</button>
  </div>
</div>

planner/templates/planner/upload_json.html
{% extends 'base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

planner/templates/planner/weeks.html
<div id="weeks" class="row">
  {% for week in weeks %}
  <div class="col-xl-4 col-md-6 col-sm-12">
    <table class="table table-hover">
      <tbody>
        {% for day in week %}
        {% include 'planner/day_table_row.html' with day=day %}
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endfor %}
</div>