dinrplan/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("planner.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

planner/urls.py
from django.urls import path

from . import views

app_name = "planner"
urlpatterns = [
    path("", views.index, name="index"),
    path("day/edit/<date>", views.EditDayView.as_view(), name="edit_day"),
    path("day/show/<date>", views.ShowDayView.as_view(), name="show_day"),
    path(
        "day/addmeal/<date>/meal_pk/<meal_pk>",
        views.AddMealToDayView.as_view(),
        name="add_meal_to_day",
    ),
    path("meal/edit/<slug:pk>", views.MealUpdateView.as_view(), name="editmeal"),
    path("meal/show/<slug:pk>", views.MealDetailView.as_view(), name="showmeal"),
    path("meal/delete/<slug:pk>", views.MealDeleteView.as_view(), name="delete_meal"),
    path(
        "meal/comment/<slug:pk>",
        views.CommentCreateView.as_view(),
        name="create_comment",
    ),
    path("upload", views.UploadJsonView.as_view(), name="upload"),
    path("update_weeks", views.UpdateDisplayedWeeksView.as_view(), name="update_weeks"),
    path("recipes", views.RecipesView.as_view(), name="recipes"),
    path("weeks", views.WeeksView.as_view(), name="weeks"),
    # Called when dragging from or dropping on a day
    path("drag/<date>", views.DragView.as_view(), name="drag"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<!-- <html lang="en"> -->

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {% load static %}
  <link rel="shortcut icon" type="image/png" href="{% static 'planner/favicon.ico' %}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
  <script src="https://unpkg.com/htmx.org@1.8.0"></script>
  <script src="https://unpkg.com/htmx.org@1.8.0/dist/ext/event-header.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/js/standalone/selectize.min.js"
    integrity="sha512-pF+DNRwavWMukUv/LyzDyDMn8U2uvqYQdJN0Zvilr6DDo/56xPDZdDoyPDYZRSL4aOKO/FGKXTpzDyQJ8je8Qw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/css/selectize.bootstrap4.min.css"
    integrity="sha512-MMojOrCQrqLg4Iarid2YMYyZ7pzjPeXKRvhW9nZqLo6kPBBTuvNET9DBVWptAo/Q20Fy11EIHM5ig4WlIrJfQw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <script src="{% static 'planner/color_mode_toggler.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'planner/index.css' %}">
  {% block head %}
  {% endblock %}
  <title>{% block title %}dinrplan{% endblock %}</title>
</head>
<!-- hx-headers is needed to be able to use other HTTP methods than GET. See https://www.mattlayman.com/blog/2021/how-to-htmx-django/ . -->

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <!-- Modal -->
  <div class="modal fade" id="mealModal" tabindex="-1" aria-labelledby="mealModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      ...
    </div>
  </div>
  <div class="container-fluid">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'planner:index' %}">
            <h1>dinrplan</h1>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'planner:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'planner:recipes' %}">Recipes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'planner:upload' %}">Upload</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  {{ user.username }}
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item theme-toggle" href="#"><i class="bi bi-sun"></i><i
                        class="bi bi-moon"></i>&nbsp;Toggle dark mode</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Log out</a></li>
                </ul>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Log in</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
  </div>
  <div class="container-fluid">
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
</body>

</html>